roadwork_detector_node:
  ros__parameters:
    confidence_threshold: 0.25
    resize_width: 640
    resize_height: 480
    target_classes: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

lidar_fusion_node:
  ros__parameters:
    lidar_to_cam_z_offset: 1.011   # from calibration matrix
    alpha_d: 0.15
    default_fx: 1000.0             # updated automatically from camera_info
    default_fy: 1000.0
    default_cx: 640.0
    default_cy: 540.0
    min_distance: 2.0              # ignore points closer than 0.5m
    max_distance: 80.0             # ignore points farther than 80m
    bbox_expand_px: 25            # expand bbox by 10px each side for LiDAR matching

confidence_node:
  ros__parameters:
    lambda_factor: 0.50
    n_max: 12
    alpha_c: 0.15

risk_node:
  ros__parameters:
    d_near: 5.0
    d_far: 30.0
    w_c: 0.50
    w_d: 0.50
    alpha_r: 0.20
